import Head from "next/head";
import {
  AiFillInstagram,
  AiFillGithub,
  AiFillLinkedin,
  AiTwotonePhone,
  AiFillMail,
  AiFillEnvironment,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/julie.png";
import Image from "next/image";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">developed by julie</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>

              <li>
                <a
                  className="bg-gradient-to-r from-pink-100 text- to-pink-300 text-black px-4 py-2 border-none rounded-md ml-8"
                  href="Julie.K.Rodriguez.pdf"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 font-medium dark:text-white md:text-6xl">
              Julie Rodriguez
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Full Stack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl"></p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.instagram.com/juliekrodriguezz">
                <AiFillInstagram />
              </a>
              <a href="https://www.linkedin.com/in/julietrodriguez1/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/juliekrodriguez">
                <AiFillGithub />
              </a>
            </div>
            <div className=" mx-auto rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <center>
                <Image
                  src={deved}
                  layout="fill"
                  objectFit="cover"
                  alt="profile pic"
                />
              </center>
            </div>
          </div>
        </section>
        <section> 
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am a dynamic software engineer based in Seattle, I have
              proficiency in full-stack application development and project
              management. I possess a robust background in successfully leading
              teams through the entire development life cycle. My educational
              qualifications include a minor in mathematics and a
              bachelor's degree in software engineering. 
              
             Beyond my professional commitments, I contribute as a
              mentor to high school students through the Society of Women
              Engineers club. I also provide tutoring services to undergraduates, specializing
             in computer science and mathematics. 
             
             My growth
              mindset, positive attitude, and commitment to excellence position
              me as a valuable asset to any team. I am consistently seeking new
              experiences and opportunities to enhance my skill set and
              contribute meaningfully to projects.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"></p>
          </div>

          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              What kind of skills do I have?
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"></p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200"></p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2  ">Languages</h3>
              <p className="text-gray-800 py-1">C</p>
              <p className="text-gray-800 py-1"> C++</p>
              <p className="text-gray-800 py-1">C#</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">TypeScript</p>
              <p className="text-gray-800 py-1">SQL</p>
              <p className="text-gray-800 py-1">Swift</p>
            </div>

            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Technology and Frameworks
              </h3>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Node</p>
              
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">Django</p>
              <p className="text-gray-800 py-1">Git</p>
              <p className="text-gray-800 py-1">Angular</p>
              <p className="text-gray-800 py-1">.NET</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <h3 className="text-lg font-medium pt-8 pb-2 ">Soft Skills</h3>
              <p className="text-gray-800 py-1">Adaptablility</p>
              <p className="text-gray-800 py-1">Communication</p>
              <p className="text-gray-800 py-1">Analytical Thinking</p>
              <p className="text-gray-800 py-1">Conflict Resolution</p>
              <p className="text-gray-800 py-1">Project Management</p>
              <p className="text-gray-800 py-1">Positive Work Ethic</p>
            </div>
          </div>
          <div className="w-full min-h-screen flex justify-center items-center ">
            <div className="flex flex-col md:flex-row space-y-6 md:space-y-0 md:items-stretch md:space-x-12 w-full max-w-4xl p-8 sm:px-12 sm:py-10 rounded-xl shadow-lg dark:text-white text-black overflow-hidden">
              <div className="md:py-4 flex-grow flex flex-col space-y-8 md:justify-between dark:text-white">
                <div className="">
                  <h1 className="font-bold text-4xl tracking-wide dark:text-white text-black">
                    Contact me
                  </h1>
                </div>

                <div className="flex flex-col space-y-6">
                  <div className="inline-flex space-x-2 items-center">
                    <AiTwotonePhone
                      name="call"
                      className="text-xl"
                    ></AiTwotonePhone>
                    <span className="select-all">+(425) 236 8555</span>
                  </div>

                  <div className="inline-flex space-x-2 items-center">
                    <AiFillMail name="mail" className="text-xl"></AiFillMail>
                    <span className="select-all">julietdevops@gmail.com</span>
                  </div>

                  <div className="inline-flex space-x-2 items-center">
                    <AiFillEnvironment
                      name="addy"
                      className="text-xl"
                    ></AiFillEnvironment>
                    <span className="select-all">Seattle, WA</span>
                  </div>
                </div>
                <div className="flex space-x-4 text-lg">
                  <a href="#" className="hover:text-black">
                    <ion-icon name="logo-facebook"></ion-icon>
                  </a>
                  <a href="#" className="hover:text-teal-300">
                    <ion-icon name="logo-twitter"></ion-icon>
                  </a>
                  <a href="#" className="hover:text-teal-300">
                    <ion-icon name="logo-linkedin"></ion-icon>
                  </a>
                  <a href="#" className="hover:text-teal-300">
                    <ion-icon name="logo-instagram"></ion-icon>
                  </a>
                </div>
              </div>
              <div className="relative z-10">
                <div className="absolute -top-28 -right-28 z-0 bg-pink-300 w-40 h-40 rounded-full"></div>
                <div className="absolute -bottom-16 -left-28 z-0 bg-pink-300 w-40 h-40 rounded-full"></div>
                <div className="relative z-10 w-full md:w-80 h-full bg-white p-8 text-gray-600 rounded-xl shadow-lg min-height: 300px">
                  <div id="error"></div>
                  <form
                    action="https://formcarry.com/s/1OGFB-27Y6"
                    method="POST"
                    acceptCharset="UTF-8"
                    className="flex flex-col space-y-4"
                  >
                    <div>
                      <label htmlFor="name">Your name</label>
                      <input
                        type="text"
                        id="name"
                        name="name"
                        className="ring-1 ring-gray-300 mt-2 w-full rounded-md px-4 py-2 outline-none focus:ring-2 focus:ring-pink-300"
                      />
                    </div>
                    <div>
                      <label htmlFor="email">Email Address</label>
                      <input
                        type="text"
                        id="Email Address"
                        name="email"
                        className="ring-1 ring-gray-300 mt-2 w-full rounded-md px-4 py-2 outline-none focus:ring-2 focus:ring-pink-300"
                      />
                    </div>
                    <div>
                      <label htmlFor="text">Message</label>
                      <textarea
                        id="message"
                        name="message"
                        className="ring-1 ring-gray-300 mt-2 w-full rounded-md px-4 py-2 outline-none focus:ring-2 focus:ring-pink-300"
                        rows="4"
                      ></textarea>
                    </div>

                    <input type="hidden" name="_gotcha"></input>

                    <button className="inline-block self-end bg-pink-300 text-white font-bold rounded-lg px-6 py-2 uppercase text-sm">
                      Submit
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
